config/routes.rb
Rails.application.routes.draw do
  root 'chat#index'
  get '/result', to: 'chat#show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  require "openai"
  require 'dotenv'
  Dotenv.load
  
  before_action :set_common_variable

  private

  # APIキーを設定
  def set_common_variable
    @client = OpenAI::Client.new(access_token: ENV["CHATGPT_API_KEY"])
  end
end

app/controllers/chat_controller.rb
class ChatController < ApplicationController
  def index
  end

  def show
    @keyword = chat_params[:keyword]

    response = @client.chat(
      parameters: {
          model: "gpt-3.5-turbo",
          messages: [{ role: "user", content: "あなたはサービスの名前を付ける天才です。斬新で、わかりやすいサービス名を思いつくことが出来ます。#{@keyword}というキーワードから、サービス名を５個日本語で考えてみてください。なぜそう考えたのかも教えてください。" }],
      })

    @chats = response.dig("choices", 0, "message", "content")
  end
  
  private

  def chat_params
    params.permit(:keyword)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chat_helper.rb
module ChatHelper
end

app/views/chat/index.html.erb
<section>
  <div class="home-about-service">
    <h1>命名の達人</h1>
    <p>
      命名の達人は、新しいWebサービスやアプリを開発する際に、そのサービス名を考える支援をするためのツールです。
      特徴や用途などのキーワードを入力することで、自動的にサービス名の候補を生成することができます。
    </p>
  </div>
  <div class="home-keyword-input-form">
    <h2>キーワード入力欄</h2>
    <div class="row d-flex justify-content-center">
      <div class="col-md-6">
        <%= form_with(url: result_path, method: :get) do |form| %>
          <div class="mb-3">
            <%= form.label :"キーワード" %>
            <%= form.text_field :keyword, { class: "form-control", placeholder: "キーワードを入力してください。" } %>
          </div>
          <div class="mb-4 d-grid gap-2 mx-auto text-center">
            <%= form.submit "サービス名を生成", class: "btn btn-warning" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <div class="home-service-consept">
    <div class="home-service-consept-about">
      <h2>コンセプト</h2>
      <p>
        個人開発で作ったアプリにどんなサービス名をつけようか迷ったことはありませんか？<br>
        そんな経験から生まれたのが「命名の達人」です。<br>
        キーワードを入力するとAIが自動でアプリ名を5つ考えてくれます。<br>
        もし気に入ったアプリ名が見つからなくても、キーワードを変えると新たなサービス名を考案してくれます。
      </p>
    </div>
    <div class="row d-flex justify-content-center">
      <div class="col-md-6">
        <%= form_with(url: result_path, method: :get) do |form| %>
          <div class="d-grid gap-2 mx-auto text-center">
            <%= form.hidden_field :keyword, value: "タスク管理アプリ" %>
            <%= form.submit "「タスク管理アプリ」を例に生成", class: "btn btn-warning" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
    
  <div class="home-how-to-use">
    <h2>使い方</h2>
    <p>
      1.キーワードを入力欄に入力する。<br>
      2.入力欄の直下にある「サービス名を生成するボタン」を押す。<br>
      3.サービス名一覧が表示される。
    </p>
  </div>
</section>

app/views/chat/show.html.erb
<section>
  <div class="show-generated">
    <h2>サービス名の生成結果</h2>
    <div class="show-generated-result">
      <%= @chats %>
    </div>
    <div class="d-grid gap-2">
      <%= link_to 'TOPページ', root_path, class:'btn btn-warning' %>
    </div>
  </div>
</section>

app/views/layouts/_footer.html.erb
<footer class="bg-primary text-light fixed-bottom">
  <div class="text-center p-3">
    &copy;2023 Takumi Koshizuka
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-dark bg-primary sticky-top">
    <div class="container-sm">
      <%= link_to '命名の達人', root_path, class: "navbar-brand" %>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- Google tag (gtag.js) -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-NQSY24CMCS"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());
    
      gtag('config', 'G-NQSY24CMCS');
    </script>
    <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-5392779818226116" crossorigin="anonymous"></script>
    <title>命名の達人</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>